language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
script:
- npm run test:unit
after_script:
- cat ./coverage/lcov.info | coveralls
deploy:
  app: usnie-ci-test
  provider: heroku
  api_key:
    secure: amRSktblSy2drCEB411TgmA6p1+aQQOJb+Hayhke7apzzSquts/3n0yJ2SFScgAAqe42Ky+3tsO7DHb9yxNu4Z6h1nJa+OBSOyLMSsTwkqXZA9Q6Ei6TOjrNivwJgIO4iHMxIYzKoDSCoHI2vFzbBI8R5v92z/dt721KbFQu/hTSzaEC6DJm1Z8bnLvMxRvnWF+OupmYZVhbpZrBr2yx06V+FItvgl8tNh/bIWEYULscodfMo8Zwlnn2LMvIS52/ry4+nbbIhUPALRqTTJmYER3JiWxypkVKxbr709xmt5cQ1E0lx3L76oKawrMBD9XNA0ZCJ06HQSHxwcHBh/DXVGjEU5Kd2n9xVJMn1rwvpV7giv0uITukQPmlezxrrvGhhiXVDvVwQYTyMhBGVNwqf0+N44z5AyTmE9XCiiVhTeRJ5aslIA+TXCJGeC41GsJI/iTdZqxBc2heRZuFAVj+fm+aebm0LuMo13ilm5zuRL8NxriZTb1Z+ohU1bG7z139EqrZzdxUxdGDV4ljYTQcEKU4lGphY4BdNdJI0KrJxNmrfEhcgM75Ws4HzDFuZrNvqTnu7wzZkj1jkCGMiu1VJPrK/zI8TuMROvb4GF3qrml/XPI2OI6Xrbtz3vJcRqGCA8We/VrAhBsuuzGqV0OSYC9twHXbaFM3CR2yx73LoVE=