language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
script:
- npm run test:unit
after_script:
- cat ./coverage/lcov.info | coveralls
deploy:
  provider: heroku
  api_key:
    secure: X2h5HxS2iFxpQ0gSvwSmZjC7yYc5e3FHSfqOaPquSuV+e/C1zOyoH1C+pH8fBEh27UyLsiPWlMMAGTI5cxys2VOS+ozBsdk9mBtEtvI8lC7tugOHvZWrBUMhpkcme2/tt4dc7KLvhLvUDoCbjo0j+zuG2G7CNC1IDlTr/gIIfb3CgTcjTbmklUZhZtBxDCndQgvqQ/oRX4PlJrAbMX7w1Gonsuqfrd9z30NbTlo0LPG/u2cYvaNg/qSEP3gJWZeHRJxOWPvXNUEvg8cXxHss3dd+3OWGrfrqbIhON8FuN46oz5VrWV7HDflBVZuJpL34gH6gDgfWv4VqE6lKEXNmjPhZ5AlpB9V5jTOFLxydVqosGM8uME7FwqKofFpJ1SThEv2M5C37y+z7hJhsFhr2Vqd5Q5SwQpFHRxWIPCHMzxE9JSHzFnQnPLYbKUjM7PLLlOlp+0N/r6+P8du7oCeRwwzlWBLZM84Gi/xDkcw/mj4FbNxEfEkx2cucJjoUuXjiX96O2e6hhk1tIaU20NaAyCLQtdjMQXjfeowkosZ9Rd2a0CHJelMPM35WLrWADgmensOsQ7Bp7sQzbc/hBoLIHgVElnEFEO80oaGoHdG0/DUA9ey6frZxTqnSlpqEQUhwOnh8rEtU1rvZ9L/UTdPWUhD9rhrf3yVxGi0FeXr98Ec=
  app: usnie-ci-test
  on:
    branch: master
