language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
script:
- npm run test:unit
after_script:
- cat ./coverage/lcov.info | coveralls
deploy:
  provider: heroku
  api_key:
    secure: GwdVNlmE1HTtvJLffMuJ76oR1bzYl7MjCTwbrXr6j+8qgG5NH6D/QuB/jWY8T+Qun5oQc+iIH1VXPNPvviZ1Mqyz/Z9Wz8uQKCvuwY1uZpzs3PQb66du1pkFMRvsMRhpbz8tBmmtcPb5LMoRW8IdVLN/A6YOgGc9n2Tnpy2bZDZG5nE8ihXntSns67fytdKZJAhKULn7x6Tb/vqPoSU6ohXZJIwxgNaX248151UHvwSG3Slil/uA5N+PT7oxZ1G7rOkTFuDLR47paQ5u4D8VDmFoZy/i52YC5W5Dnzr3/fL+i95lkddCUnOvztj6vBB+H/u/PpnfIxPlaN7xGCUzK96dWKfS7iNM+uydodeKm/u1mz+GKuUF9I/YrUNUDO5WK/rmY8KpitGySVH4LDmVgqG2YkPv3YbMthXdMAUryR1NdVs7y6RZQdncoITbKdvsjVLxphUiMVO3kWRlgnT3RrTRVK7M3cIA1XLloMH8CRcG6NcmBFU98LdNd1sfUfZsQclNWbB+/GTgzgI+letd3caQ54kJ24vW7HMsHgblWlPep3oWYruycy1HCOvOcPt/jEr4Q5P7VS9Xdn1FwXeq9VjqcVpB+GGLu7WK+bdJTu8DFJXd5vk2qMoZ2p+m1ra/RWPopf4/cjCx0SywgzZW3XK1t0JIMLpeB+cUwM+R/SY=
  app: usnie-ci-test
  on:
    branch: master
