language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
script:
- npm run test:unit
after_script:
- cat ./coverage/lcov.info | coveralls
deploy:
  provider: heroku
  api_key:
    secure: Go+kfrdqnRLGZkT0gtczuACiH25iOEa2VHVP6xblPA+ajWVb5xoSMkZWWxInr+t5icDLdZJ1RCyZjkmEDx57lIFArhiE+SguKbdJZ229IgiRqUdKlxQpAH/M0cgtkxHI3wuwcMxWnhGdg2i0KN5u3FQ0j1xyTfh636U2eOD7r8Ecei6UqrQySOflTjmeJhwMtomPyiwd2OQLieuyVophZ/kuM+T8LQcSO8jhzD4XH7m/2135YCOmkML3WgtYXSOizmaO6rQ83U5f0dKgMR4yQBvpwCfb7lQrOYUcLMn0PMTKPRZeLa3hibyjGm+HYgAUHaWvnMxfmV4aXffJemRiug0owKMjt4pHFjmYanJ/YcRj8FYrotpwDDYGw/J64GxNyY+kOwlvDZMSMWv2Obu6DpaQrOVsBRLoDhiBG7RUa9YopRvyG3w9yXfbIwOkEzSRIgkNkm/xMGo0tNLVfoUqm7yQLXWi8jdBvU8uJlhRdAx/UCyXiQA433UQP/JlKFACbEFqZV3RLmf0ICDgDUcqynN4Re1G8EB66xHU8b4vhN5MlebyedeY49y8Too8E+9DEbYwBBYTqG0krgl0iX0EvOLum7E1nXuM/iWK7znsT1QcsRmsFZQTHboegbSONs6KzkRaAwHBEwkAmONr9+ZxJ8ndgehzVJE39SO8emuutr4=
  app: usnie-ci-test
  on:
    branch: master
